src/java/model/User.java
package model;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import static model.DatabaseInfo.dbURL;
import static model.DatabaseInfo.driverName;
import static model.DatabaseInfo.passDB;
import static model.DatabaseInfo.userDB;

/**
 *
 * @author khanhlvm98
 */
public class User implements DatabaseInfo{
    String username;
    String fullname;
    String userpass;
    String dob;
    Boolean gender;
    String email;
    String phone;
    String userLocation;
    String bio;
    String addDate;   

    public User() {
    }   
    
    public User(String username, String fullname, String userpass, String dob, Boolean gender) {
        this.username = username;
        this.fullname = fullname;
        this.userpass = userpass;
        this.dob = dob;
        this.gender = gender;     
    }
    
    public User(String username, String fullname, String userpass, String dob, Boolean gender, String email, String phone, String userLocation, String bio) {
        this.username = username;
        this.fullname = fullname;
        this.userpass = userpass;
        this.dob = dob;
        this.gender = gender;
        this.email = email;
        this.phone = phone;
        this.userLocation = userLocation;
        this.bio = bio;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserpass() {
        return userpass;
    }

    public void setUserpass(String userpass) {
        this.userpass = userpass;
    }
    
    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    
    public String getDob() {        
        return dob;
    }

    public void setDob(String dob) {
        this.dob = dob;
    }

    public String isGender() {
        return gender?"M":"F";
    }

    public void setGender(String gender) {
        this.gender = gender.equals("M");
    }
    
    public String getGender() {
        return gender?"Male":"Female";
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getUserLocation() {
        return userLocation;
    }

    public void setUserLocation(String userLocation) {
        this.userLocation = userLocation;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }  
    
    public String getAddDate() {
        return addDate;
    }

    public void setAddDate(String addDate) {
        this.addDate = addDate;
    }
    
    public User(String username) {
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "SELECT * FROM UserTB WHERE username=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                this.username = rs.getString(1);
                fullname = rs.getString(2);
                userpass = rs.getString(3);
                dob = rs.getString(4);
                gender = rs.getString(5).equals("M");
                email = rs.getString(6);
                phone = rs.getString(7);
                userLocation = rs.getString(8);
                bio = rs.getString(9);
            }
            con.close();
        }catch(Exception e) {
            e.printStackTrace();
        }      
    }
    
    public boolean createAccount(User u){    
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "INSERT INTO UserTB(username,fullname,userpass,dob,gender) VALUES(?,?,?,?,?)";           
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, u.getUsername());
            ps.setString(2, u.getFullname());
            ps.setString(3, u.getUserpass());
            ps.setString(4, u.getDob());
            ps.setString(5, u.isGender());
            ps.executeUpdate(); 
            con.close();
            return true;
        }catch(Exception e) {
            e.printStackTrace();
        }                
        return false;
    }
    
    public boolean checkLogin(String username, String password) {
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "SELECT * FROM UserTB WHERE username=? "
                    + "AND userpass=? ";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, username);
            ps.setString(2, password);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                return true;
            }
            con.close();
        }catch(Exception e) {
            e.printStackTrace();
        }
        return false;
    }
    
    public boolean updateUser(User u){
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "UPDATE UserTB SET fullname=?, dob=?, gender=?, email=?, phone=?, userLocation=?, bio=? WHERE username = ?";
            PreparedStatement ps = con.prepareStatement(sql);            
            ps.setString(1, u.getFullname());
            ps.setString(2, u.getDob());
            ps.setString(3, u.isGender());
            ps.setString(4, u.getEmail());
            ps.setString(5, u.getPhone());
            ps.setString(6, u.getUserLocation());
            ps.setString(7, u.getBio());
            ps.setString(8, u.getUsername());
            ps.executeUpdate();
            con.close();
            return true;
        }catch(Exception e) {
            e.printStackTrace();
        }                
        return false;
    }
    
    public boolean updatePassword(String username, String userpass){
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "UPDATE UserTB SET userpass=? WHERE username = ?";
            PreparedStatement ps = con.prepareStatement(sql);            
            ps.setString(1, userpass);
            ps.setString(2, username);
            ps.executeUpdate();
            con.close();
            return true;
        }catch(Exception e) {
            e.printStackTrace();
        }                
        return false;
    }
    
    public User getUser(String username) {
        User u = new User();
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "SELECT * FROM UserTB WHERE username=?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, username);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                String uname = rs.getString(1);
                String ufname = rs.getString(2);
                String upass = rs.getString(3);
                String udob = rs.getString(4);
                String ugender = rs.getString(5);
                String uemail = rs.getString(6);
                String uphone = rs.getString(7);
                String uLocation = rs.getString(8);
                String ubio = rs.getString(9);
                u = new User(uname,ufname,upass,udob,ugender.equals("M"),uemail,uphone,uLocation,ubio);
                return u;
            }
            con.close();
        }catch(Exception e) {
            e.printStackTrace();
        }
        return u;
    }
    
    public ArrayList<User> getAllUser() {
        ArrayList<User> al = new ArrayList<>();
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "SELECT * FROM UserTB";
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(sql);
            while(rs.next()){
                String uname = rs.getString(1);
                String ufname = rs.getString(2);
                String upass = rs.getString(3);
                String udob = rs.getString(4);
                String ugender = rs.getString(5);
                String uemail = rs.getString(6);
                String uphone = rs.getString(7);
                String uLocation = rs.getString(8);
                String ubio = rs.getString(9);
                User u = new User(uname,ufname,upass,udob,ugender.equals("M"),uemail,uphone,uLocation,ubio);
                al.add(u);
            }
            con.close();
        }catch(Exception e) {
            e.printStackTrace();
        }
        return al;
    }
    
    public boolean addFriend(String user1, String user2, int statusFriend, String addDate){    
        try{
            Class.forName(driverName);
            Connection con = DriverManager.getConnection(dbURL,userDB,passDB);
            String sql = "INSERT INTO FriendTB(username_1,username_2,statusFriend,addDate) VALUES(?,?,?,?)";           
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, user1);
            ps.setString(2, user2);
            ps.setInt(3, statusFriend);
            ps.setString(4, addDate);
            ps.executeUpdate(); 
            con.close();
            return true;
        }catch(Exception e) {
            e.printStackTrace();
        }                
        return false;
    }
    

src/java/controller/CreateServlet.java
package controller;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import model.Activity;
import model.User;

/**
 *
 * @author khanhlvm98
 */
public class CreateServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        request.getRequestDispatcher("create.jsp").include(request, response);
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession ss = request.getSession();
        if(ss.getAttribute("ac")==null){
            request.getRequestDispatcher("create.jsp").include(request, response);
        }
        User u = (User)ss.getAttribute("u");
        Activity a = (Activity)ss.getAttribute("ac");
        Activity ja = new Activity(a.getActID(),u.getUsername(),String.valueOf(java.time.LocalDate.now()));  
        if( (a.createActivity(a, u.getUsername())) && (ja.setJoin(ja)) ) {
            request.getRequestDispatcher("manage.jsp?success=1").include(request, response);
            ss.invalidate();
        }else{
            request.getRequestDispatcher("create-confirm.jsp?error=0").include(request, response);
        }
        response.setContentType("text/html;charset=UTF-8");
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/java/controller/DeleteServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import model.Activity;
import model.User;

/**
 *
 * @author khanhlvm98
 */
public class DeleteServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");        
        
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        String actID = request.getParameter("actID");
        Activity a = new Activity(Integer.valueOf(actID));
        HttpSession ss = request.getSession();
        request.getSession().setAttribute("ad", a);
        request.getRequestDispatcher("delete.jsp").include(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        HttpSession ss = request.getSession();
        Activity a = (Activity)ss.getAttribute("ad");
        if( a.unJoin(a.getActID()) && a.deleteActivity(a.getActID())) {
            request.getRequestDispatcher("manage.jsp?success=1").include(request, response);
        }else{
            request.getRequestDispatcher("delete.jsp?error=0").include(request, response);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

web/changepass.jsp
<%-- 
    Document   : index
    Created on : Oct 31, 2019, 4:26:56 PM
    Author     : khanhlvm98
--%>

<%@page import="model.User"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<jsp:useBean id="us" class="model.User" scope="session"/>
<jsp:useBean id="act" class="model.Activity" scope="session"/>
<!DOCTYPE HTML>

<html>
<head>
        <title>Change password</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <link rel="stylesheet" href="assets/css/main.css" />
        <style>
            strong{color:#3eb08f}
        </style>
</head>
<body class="is-preload">

<!-- Header -->
<header id="header">
    <div class="row">
        <div class="col-6 col-12-xsmall">
            <a href="#" class="image avatar"><img src="images/avatar.jpg"/></a>                                   
        </div>
        <div class="col-6 col-12-xsmall">
            <a href="home">Home</a>
            <br/>
            <a href="profile?username=${u.username}">Profile Details</a>
            <br/>
            <a href="create">Create Activities</a>
            <br/>
            <a href="manage">Manage Activities</a>
            <br/>
            <a href="logout">Logout</a>
        </div>
    </div>
    <div class="row">
        <h3><strong>${u.fullname}</strong></h3>
    </div>                           
    <hr/>
    <h4>People you may know</h4>
    <c:forEach items="${us.allUser}" var="uf">
        <c:if test="${us.allUser!= null && us.getFriend(u.username,uf.username) != 1 && uf.username != u.username}">
            <ul class="actions fit">
                <li><a href="profile?username=${uf.username}" class="fit"> ${uf.getUser(uf.username).fullname} </a></li>
                <li><a href="addfriend?username=${uf.username}" class="button small fit">Add friend</a></li></ul>
        </c:if>
    </c:forEach>         
</header>

<!-- Main -->
<div id="main">
<!-- One -->
<section id="one">               
    <header class="major">    
        <c:if test="${param.error == 0}"> 
            <h2><strong>Error...! Check again!</strong></h2>
        </c:if>
        <h2>CHANGE PASSWORD</h2>
        <form action="changepass" method="post" style="color:#3eb08f">
            <div class="row gtr-uniform gtr-50">
                <div class="col-4 col-12-xsmall">                               
                    <label>Current Password: </label>
                </div>
                <div class="col-8 col-12-xsmall">
                    <input type="password" name="userpass" placeholder="********">
                    <a href="#">Forgot password?</a>
                </div> 
                <div class="col-4 col-12-xsmall">                               
                    <label>New Password: </label>
                </div>
                <div class="col-8 col-12-xsmall">
                    <input type="password" name="newpass" placeholder="********">
                    <c:choose>
                        <c:when test="${param.failure==1}"><p><strong>Error... . password less 8 character</strong></p></c:when>
                        <c:otherwise></c:otherwise>
                    </c:choose>
                </div>

                <div class="col-4 col-12-xsmall">                               
                    <label>Confirm Password: </label>
                </div>
                <div class="col-8 col-12-xsmall">
                    <input type="password" name="confirmpass" placeholder="********">
                </div>                            
                <div class="col-12">
                    <ul class="actions">
                        <li><input type="submit" value="CHANGE" class="primary"></li>
                        <li><a href="profile" class="button">Back to profile</a></li>
                    </ul>
                </div>                           
            </div>
        </form>
    </header>
</section>                                        
</div>
<!-- Footer -->
        <footer id="footer">
            <div class="inner">
                <ul class="copyright">
                    <li>&copy; 2019 Untitled</li><br>   
                    <a href="#">Terms   |</a>
                    <a href="#">Privacy    |</a>
                    <a href="#">Security    </a>
                </ul>
            </div>
        </footer>

<!-- Scripts -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/jquery.poptrox.min.js"></script>
        <script src="assets/js/browser.min.js"></script>
        <script src="assets/js/breakpoints.min.js"></script>
        <script src="assets/js/util.js"></script>
        <script src="assets/js/main.js"></script>
</body>
</html>

web/create-confirm.jsp
<%-- 
    Document   : index
    Created on : Oct 31, 2019, 4:26:56 PM
    Author     : khanhlvm98
--%>

<%@page import="model.User"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<jsp:useBean id="us" class="model.User" scope="session"/>
<jsp:useBean id="ac" class="model.Activity" scope="session"/>
<jsp:setProperty name="ac" property="*"/>
<!DOCTYPE HTML>

<html>
<head>
        <title>Creation Confirm</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <link rel="stylesheet" href="assets/css/main.css" />
        <style>
            strong{color:#3eb08f}
        </style>
</head>
<body class="is-preload">
<!-- Header -->
<header id="header">
    <div class="row">
        <div class="col-6 col-12-xsmall">
            <a href="#" class="image avatar"><img src="images/avatar.jpg"/></a>                                   
        </div>
        <div class="col-6 col-12-xsmall">
            <a href="home">Home</a>
            <br/>
            <a href="profile?username=${u.username}">Profile Details</a>
            <br/>
            <a href="create">Create Activities</a>
            <br/>
            <a href="manage">Manage Activities</a>
            <br/>
            <a href="logout">Logout</a>
        </div>
    </div>
    <div class="row">
        <h3><strong>${u.fullname}</strong></h3>
    </div>                           
    <hr/>
    <h4>People you may know</h4>
    <c:forEach items="${us.allUser}" var="uf">
        <c:if test="${us.allUser!= null && us.getFriend(u.username,uf.username) != 1 && uf.username != u.username}">
            <ul class="actions fit">
                <li><a href="profile?username=${uf.username}" class="fit"> ${uf.getUser(uf.username).fullname} </a></li>
                <li><a href="addfriend?username=${uf.username}" class="button small fit">Add friend</a></li></ul>
        </c:if>
    </c:forEach>         
</header>

<!-- Main -->
<div id="main">
<!-- One -->
<section id="one">               
    <header class="major">    
        <c:if test="${param.error == 0}"> 
            <h2><strong>Error...! Check again!</strong></h2>
        </c:if>
        <h2>CREATION CONFIRM</h2>
        <form action="create" method="post" style="color:#3eb08f">
            <div class="row gtr-uniform gtr-50">
                <div class="col-3 col-12-xsmall">
                    <input type="text" name="actID" id="demo-name" value="${ac.actID}">
                </div>
                <div class="col-6 col-12-xsmall">
                    <input type="text" name="actName" id="demo-name" value="${ac.actName}">
                </div>
                <div class="col-3 col-12-xsmall">
                    <select name="categories" id="demo-category">   
                        <option>${ac.categories}</option>  
                        <option value="Art">Art</option>
                        <option value="Causes">Causes</option>
                        <option value="Comedy">Comedy</option>
                        <option value="Crafts">Crafts</option>
                        <option value="Dance">Dance</option>
                        <option value="Drinks">Drinks</option>
                        <option value="Film">Film</option>
                        <option value="Fitness">Fitness</option>
                        <option value="Food">Food</option>
                        <option value="Games">Games</option>
                        <option value="Gardening">Gardening</option>
                        <option value="Health">Health</option>
                        <option value="Home">Home</option>
                        <option value="Literature">Literature</option>
                        <option value="Music">Music</option>
                        <option value="Networking">Networking</option>
                        <option value="Other">Other</option>
                        <option value="Party">Party</option>
                        <option value="Religion">Religion</option>
                        <option value="Shopping">Shopping</option>
                        <option value="Sports">Sports</option>
                        <option value="Theater">Theater</option>
                        <option value="Wellness">Wellness</option>
                    </select>
                </div>
                <div class="col-6 col-12-xsmall">
                    <input type="text" name="actLocation" value="${ac.actLocation}"/> <br />
                </div>
                <div class="col-3 col-12-xsmall">
                    <input type="time" name="actTime" id="demo-name" value="${ac.actTime}">
                </div>
                <div class="col-3 col-12-xsmall">
                    <input type="date" name="actDate" id="demo-name" value="${ac.actDate}">
                </div>                                                                                                       
                <div class="col-12">
                    <textarea name="description" id="demo-message" rows="3">${ac.description}</textarea>
                </div>                            
                <div class="col-12">
                    <ul class="actions">
                        <li><input type="submit" value="COMFIRM" class="primary"></li>
                    </ul>
                </div>                           
            </div>
        </form>
        <ul class="actions">
            <li><input type="submit" value="BACK" onclick="javascript:history.go(-1)"></li>
        </ul>
    </header>
</section>                                        
<!-- Two -->
<section id="two">    
    <h2>ACTIVITIES BY YOU</h2>
            <div class="row">
                <c:forEach items="${act.allActivity}" var="a">
                <article class="col-6 col-12-xsmall work-item">
                        <a href="images/fulls/cover.jpg" class="image fit thumb"><img src="images/thumbs/cover.jpg" alt="" /></a>
                        <h2><strong>${a.actName}</strong></h2>
                    <div class="table-wrapper">
                            <table>
                                <thead>
                                    <tr>
                                        <th>Location</th>
                                        <th>Time</th>
                                        <th>Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <tr>
                                            <td>${a.actLocation}</td>
                                            <td>${a.actTime}</td>
                                            <td>${a.actDate}</td>										
                                        </tr>
                                </tbody>
                                <thead>
                                    <tr>
                                        <th>Category</th>
                                        <th>Description</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <tr>
                                            <td>${a.categories}</td>
                                            <td>${a.description}</td>	
                                            <td></td>
                                        </tr>
                                </tbody>
                            </table>
                    </div>
                    <ul class="actions fit">
                        <li><a href="#" class="button fit">Like</a></li>
                        <li><a href="#" class="button fit">Join</a></li>
                        <li><a href="#" class="button fit">Members</a></li>
                    </ul>
                    <hr>
                </article>
                </c:forEach>
            </div>						                                         
</section>
</div>
<!-- Footer -->
    <footer id="footer">
        <div class="inner">
            <ul class="copyright">
                <li>&copy; 2019 Untitled</li><br>   
                <a href="#">Terms   |</a>
                <a href="#">Privacy    |</a>
                <a href="#">Security    </a>
            </ul>
        </div>
    </footer>

<!-- Scripts -->
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/js/jquery.poptrox.min.js"></script>
        <script src="assets/js/browser.min.js"></script>
        <script src="assets/js/breakpoints.min.js"></script>
        <script src="assets/js/util.js"></script>
        <script src="assets/js/main.js"></script>
</body>
</html>